import 'controller/cart_controller.dart';import 'package:ecommerce_buyers_app/core/app_export.dart';import 'package:ecommerce_buyers_app/presentation/blank_cart_page/blank_cart_page.dart';import 'package:ecommerce_buyers_app/presentation/home_page/home_page.dart';import 'package:ecommerce_buyers_app/presentation/profile_page/profile_page.dart';import 'package:ecommerce_buyers_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:ecommerce_buyers_app/widgets/app_bar/appbar_title.dart';import 'package:ecommerce_buyers_app/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'package:ecommerce_buyers_app/widgets/app_bar/custom_app_bar.dart';import 'package:ecommerce_buyers_app/widgets/custom_bottom_bar.dart';import 'package:ecommerce_buyers_app/widgets/custom_elevated_button.dart';import 'package:ecommerce_buyers_app/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';class CartScreen extends GetWidget<CartController> {const CartScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 2.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(children: [Container(padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 18.v), decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.customBorderTL40), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 5.h), child: Text("lbl_free_shipping".tr.toUpperCase(), style: CustomTextStyles.bodySmallPoppinsGray50011))), SizedBox(height: 5.v), _buildProductDetails2(), SizedBox(height: 39.v), _buildProductDetails5(), SizedBox(height: 20.v), Divider(color: appTheme.gray30001), SizedBox(height: 18.v), _buildProductDetails6(), SizedBox(height: 4.v)])), SizedBox(height: 26.v), _buildOrderSummary(), SizedBox(height: 34.v), CustomElevatedButton(text: "lbl_checkout".tr, margin: EdgeInsets.symmetric(horizontal: 24.h), buttonTextStyle: CustomTextStyles.titleLargeWhiteA700, onPressed: () {onTapCheckout();})]))))])), bottomNavigationBar: _buildBottomBar())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 66.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 7.v, bottom: 7.v), onTap: () {onTapArrowDown();}), centerTitle: true, title: AppbarTitle(text: "lbl_cart".tr), actions: [AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgFramePrimarycontainer, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 18.v))]); } 
/// Section Widget
Widget _buildProductDetails2() { return Padding(padding: EdgeInsets.only(left: 2.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Container(margin: EdgeInsets.only(right: 8.h), padding: EdgeInsets.symmetric(horizontal: 4.h, vertical: 5.v), decoration: AppDecoration.fillBlueAC.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Column(mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.symmetric(horizontal: 1.h), child: _buildProductDetails()), SizedBox(height: 5.v), Container(width: 146.h, margin: EdgeInsets.only(right: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(height: 69.v, width: 75.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.centerLeft, child: Container(height: 69.adaptSize, width: 69.adaptSize, margin: EdgeInsets.only(left: 1.h), decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(6.h)))), CustomImageView(imagePath: ImageConstant.imgDCc1, height: 40.v, width: 75.h, alignment: Alignment.topCenter, margin: EdgeInsets.only(top: 12.v))])), _buildF(moreCounterText: "lbl_2_more".tr)]))]))), Padding(padding: EdgeInsets.only(left: 8.h), child: _buildProductDetails1(title: "lbl_150".tr, subtitle: "lbl_249".tr, rating: "lbl_4_8".tr, price: "lbl_890".tr, electricPackage: "msg_electric_package".tr, description: "msg_headphone_buds2".tr, label1: "lbl".tr, label2: "lbl_1".tr, label3: "lbl2".tr))])); } 
/// Section Widget
Widget _buildProductDetails5() { return Padding(padding: EdgeInsets.only(left: 2.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Container(margin: EdgeInsets.only(right: 8.h), padding: EdgeInsets.symmetric(horizontal: 4.h, vertical: 5.v), decoration: AppDecoration.fillBlueAC.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Column(mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.symmetric(horizontal: 1.h), child: _buildProductDetails()), SizedBox(height: 5.v), Container(width: 146.h, margin: EdgeInsets.only(right: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(height: 69.v, width: 75.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.centerLeft, child: Container(height: 69.adaptSize, width: 69.adaptSize, margin: EdgeInsets.only(left: 1.h), decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(6.h)))), CustomImageView(imagePath: ImageConstant.imgDCc1, height: 40.v, width: 75.h, alignment: Alignment.topCenter, margin: EdgeInsets.only(top: 12.v))])), _buildF(moreCounterText: "lbl_2_more".tr)]))]))), Padding(padding: EdgeInsets.only(left: 8.h), child: _buildProductDetails1(title: "lbl_150".tr, subtitle: "lbl_249".tr, rating: "lbl_4_8".tr, price: "lbl_890".tr, electricPackage: "msg_electric_package".tr, description: "msg_headphone_buds2".tr, label1: "lbl".tr, label2: "lbl_1".tr, label3: "lbl2".tr))])); } 
/// Section Widget
Widget _buildProductDetails6() { return Padding(padding: EdgeInsets.only(left: 2.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Container(margin: EdgeInsets.only(right: 8.h), padding: EdgeInsets.symmetric(horizontal: 4.h, vertical: 5.v), decoration: AppDecoration.fillBlueAC.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Column(mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.symmetric(horizontal: 1.h), child: _buildProductDetails()), SizedBox(height: 5.v), Container(width: 146.h, margin: EdgeInsets.only(right: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(height: 69.v, width: 75.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.centerLeft, child: Container(height: 69.adaptSize, width: 69.adaptSize, margin: EdgeInsets.only(left: 1.h), decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(6.h)))), CustomImageView(imagePath: ImageConstant.imgDCc1, height: 40.v, width: 75.h, alignment: Alignment.topCenter, margin: EdgeInsets.only(top: 12.v))])), _buildF(moreCounterText: "lbl_2_more".tr)]))]))), Padding(padding: EdgeInsets.only(left: 8.h), child: _buildProductDetails1(title: "lbl_150".tr, subtitle: "lbl_249".tr, rating: "lbl_4_8".tr, price: "lbl_890".tr, electricPackage: "msg_electric_package".tr, description: "msg_headphone_buds2".tr, label1: "lbl".tr, label2: "lbl_1".tr, label3: "lbl2".tr))])); } 
/// Section Widget
Widget _buildOrderSummary() { return Container(padding: EdgeInsets.symmetric(horizontal: 22.h), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 2.h), child: Text("lbl_order_summery".tr, style: CustomTextStyles.titleMediumGray900))), SizedBox(height: 5.v), Padding(padding: EdgeInsets.symmetric(horizontal: 2.h), child: _buildDiscount(discountText: "lbl_items_total".tr, priceText: "lbl_850_00".tr)), SizedBox(height: 3.v), Padding(padding: EdgeInsets.symmetric(horizontal: 2.h), child: _buildDiscount(discountText: "lbl_discount".tr, priceText: "lbl_1_00".tr)), SizedBox(height: 4.v), Padding(padding: EdgeInsets.symmetric(horizontal: 2.h), child: _buildDiscount(discountText: "lbl_shipping_cost".tr, priceText: "lbl_0_00".tr)), SizedBox(height: 8.v), Divider(color: appTheme.gray30001), SizedBox(height: 4.v), Padding(padding: EdgeInsets.symmetric(horizontal: 2.h), child: _buildDiscount(discountText: "lbl_grand_total".tr, priceText: "lbl_849_00".tr))])); } 
/// Section Widget
Widget _buildBottomBar() { return CustomBottomBar(onChanged: (BottomBarEnum type) {Get.toNamed(getCurrentRoute(type), id: 1);}); } 
/// Common widget
Widget _buildProductDetails() { return SizedBox(width: 145.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(height: 69.adaptSize, width: 69.adaptSize, padding: EdgeInsets.all(5.h), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: CustomImageView(imagePath: ImageConstant.img5d02da5df552836, height: 58.adaptSize, width: 58.adaptSize, alignment: Alignment.center)), Container(height: 69.adaptSize, width: 69.adaptSize, padding: EdgeInsets.all(5.h), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: CustomImageView(imagePath: ImageConstant.imgHuaweiFreebuds, height: 58.adaptSize, width: 58.adaptSize, alignment: Alignment.center))])); } 
/// Common widget
Widget _buildF({required String moreCounterText}) { return Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), color: appTheme.whiteA700, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder6), child: Container(height: 69.adaptSize, width: 69.adaptSize, decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.img9447441f632825, height: 47.v, width: 62.h, alignment: Alignment.center), Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 24.v), decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Text(moreCounterText, style: CustomTextStyles.bodySmallPoppinsWhiteA70012_1.copyWith(color: appTheme.whiteA700))))]))); } 
/// Common widget
Widget _buildProductDetails1({required String title, required String subtitle, required String rating, required String price, required String electricPackage, required String description, required String label1, required String label2, required String label3, }) { return Expanded(child: SizedBox(width: double.maxFinite, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Text(title, style: theme.textTheme.titleSmall!.copyWith(color: appTheme.gray900)), Container(height: 15.v, width: 29.h, margin: EdgeInsets.only(left: 2.h), child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: Text(subtitle, style: CustomTextStyles.bodySmallGray40003.copyWith(color: appTheme.gray40003))), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 6.v), child: SizedBox(width: 29.h, child: Divider())))])), Container(width: 58.h, margin: EdgeInsets.only(left: 25.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgComponent1Onprimarycontainer, height: 14.adaptSize, width: 14.adaptSize), Padding(padding: EdgeInsets.only(left: 2.h), child: Text(rating, style: theme.textTheme.bodySmall!.copyWith(color: theme.colorScheme.onError))), Padding(padding: EdgeInsets.only(left: 1.h), child: Text(price, style: theme.textTheme.bodySmall!.copyWith(color: theme.colorScheme.onError)))]))]), SizedBox(height: 11.v), Text(electricPackage, style: CustomTextStyles.titleSmallPoppins.copyWith(color: appTheme.gray900)), SizedBox(width: 155.h, child: Text(description, maxLines: 3, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodySmallPoppinsGray500.copyWith(color: appTheme.gray500))), SizedBox(height: 18.v), SizedBox(width: 156.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomIconButton(height: 34.v, width: 42.h, padding: EdgeInsets.all(5.h), decoration: IconButtonStyleHelper.fillPink, child: CustomImageView(imagePath: ImageConstant.imgFrame33762)), Container(width: 104.h, padding: EdgeInsets.symmetric(vertical: 1.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(mainAxisAlignment: MainAxisAlignment.spaceAround, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text(label1, style: CustomTextStyles.bodyLargeGray500.copyWith(color: appTheme.gray500))), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 4.v), child: Text(label2, style: theme.textTheme.bodyLarge!.copyWith(color: appTheme.gray900))), Text(label3, style: CustomTextStyles.bodyLarge19.copyWith(color: appTheme.gray900))]))]))]))); } 
/// Common widget
Widget _buildDiscount({required String discountText, required String priceText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(discountText, style: CustomTextStyles.bodyLargeRed300.copyWith(color: appTheme.red300)), Text(priceText, style: CustomTextStyles.bodyLargeRed300.copyWith(color: appTheme.red300))]); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.homePage; case BottomBarEnum.Cart: return AppRoutes.blankCartPage; case BottomBarEnum.Search: return "/"; case BottomBarEnum.Profile: return AppRoutes.profilePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.homePage: return HomePage(); case AppRoutes.blankCartPage: return BlankCartPage(); case AppRoutes.profilePage: return ProfilePage(); default: return DefaultWidget();} } 
/// Navigates to the packageScreen when the action is triggered.
onTapArrowDown() { Get.toNamed(AppRoutes.packageScreen, ); } 
/// Navigates to the signinScreen when the action is triggered.
onTapCheckout() { Get.toNamed(AppRoutes.signinScreen, ); } 
 }
