import 'controller/payment_controller.dart';import 'package:ecommerce_buyers_app/core/app_export.dart';import 'package:ecommerce_buyers_app/presentation/blank_cart_page/blank_cart_page.dart';import 'package:ecommerce_buyers_app/presentation/home_page/home_page.dart';import 'package:ecommerce_buyers_app/presentation/profile_page/profile_page.dart';import 'package:ecommerce_buyers_app/widgets/custom_bottom_bar.dart';import 'package:ecommerce_buyers_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class PaymentScreen extends GetWidget<PaymentController> {const PaymentScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 165.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 5.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgGroup, height: 165.v, width: 162.h), SizedBox(height: 27.v), Container(width: 240.h, margin: EdgeInsets.only(left: 49.h, right: 36.h), child: Text("msg_your_order_has_been".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.headlineLarge!.copyWith(height: 1.25))), SizedBox(height: 7.v), Container(width: 249.h, margin: EdgeInsets.only(left: 36.h, right: 40.h), child: Text("msg_thanks_your_for".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumGray600.copyWith(height: 1.71))), SizedBox(height: 27.v), CustomElevatedButton(height: 65.v, text: "lbl_go_to_home".tr, buttonTextStyle: CustomTextStyles.titleLargeWhiteA700, onPressed: () {onTapGoToHome();})]))))])), bottomNavigationBar: _buildBottomBar())); } 
/// Section Widget
Widget _buildBottomBar() { return CustomBottomBar(onChanged: (BottomBarEnum type) {Get.toNamed(getCurrentRoute(type), id: 1);}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.homePage; case BottomBarEnum.Cart: return AppRoutes.blankCartPage; case BottomBarEnum.Search: return "/"; case BottomBarEnum.Profile: return AppRoutes.profilePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.homePage: return HomePage(); case AppRoutes.blankCartPage: return BlankCartPage(); case AppRoutes.profilePage: return ProfilePage(); default: return DefaultWidget();} } 
/// Navigates to the homeContainerScreen when the action is triggered.
onTapGoToHome() { Get.toNamed(AppRoutes.homeContainerScreen, ); } 
 }
