import 'controller/cancel_order_controller.dart';import 'package:ecommerce_buyers_app/core/app_export.dart';import 'package:ecommerce_buyers_app/presentation/blank_cart_page/blank_cart_page.dart';import 'package:ecommerce_buyers_app/presentation/home_page/home_page.dart';import 'package:ecommerce_buyers_app/presentation/profile_page/profile_page.dart';import 'package:ecommerce_buyers_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:ecommerce_buyers_app/widgets/app_bar/appbar_title.dart';import 'package:ecommerce_buyers_app/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:ecommerce_buyers_app/widgets/app_bar/custom_app_bar.dart';import 'package:ecommerce_buyers_app/widgets/custom_bottom_bar.dart';import 'package:flutter/material.dart';class CancelOrderScreen extends GetWidget<CancelOrderController> {const CancelOrderScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 24.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 23.h, right: 23.h, bottom: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_cancelled".tr, style: CustomTextStyles.bodyMediumOnPrimaryContainer), SizedBox(height: 7.v), SizedBox(width: 86.h, child: Divider(color: theme.colorScheme.onPrimaryContainer))]), GestureDetector(onTap: () {onTapTxtCompleted();}, child: Padding(padding: EdgeInsets.only(left: 28.h, bottom: 6.v), child: Text("lbl_completed".tr, style: theme.textTheme.bodyMedium)))]), SizedBox(height: 19.v), Column(children: [_buildOrderDetails2(), SizedBox(height: 20.v), Divider(color: appTheme.gray30001), SizedBox(height: 17.v), _buildOrderDetails5()])]))))])), bottomNavigationBar: _buildBottomBar())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 67.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 25.h, top: 7.v, bottom: 7.v)), centerTitle: true, title: AppbarTitle(text: "lbl_cancel_order".tr), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.imgComponent52Primarycontainer, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 7.v))]); } 
/// Section Widget
Widget _buildOrderDetails2() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_order_id_aa1254ng".tr, style: CustomTextStyles.bodySmallPoppinsBlack900), SizedBox(height: 6.v), Text("msg_placed_on_14_dec2".tr, style: CustomTextStyles.bodySmallPoppinsGray50001), SizedBox(height: 11.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(padding: EdgeInsets.symmetric(horizontal: 4.h, vertical: 5.v), decoration: AppDecoration.fillBlueAC.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Column(mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.symmetric(horizontal: 1.h), child: _buildOrderDetails()), SizedBox(height: 5.v), Container(width: 146.h, margin: EdgeInsets.only(right: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(height: 69.v, width: 75.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.centerLeft, child: Container(height: 69.adaptSize, width: 69.adaptSize, margin: EdgeInsets.only(left: 1.h), decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(6.h)))), CustomImageView(imagePath: ImageConstant.imgDCc1, height: 40.v, width: 75.h, alignment: Alignment.topCenter, margin: EdgeInsets.only(top: 12.v))])), _buildF(moreCounter: "lbl_2_more".tr)]))])), Padding(padding: EdgeInsets.only(bottom: 9.v), child: _buildOrderDetails1(electricPackageText: "msg_electric_package".tr, descriptionText: "msg_headphone_buds2".tr, itemsCounterText: "lbl_05_items".tr, priceText: "lbl_150".tr, buyAgainText: "lbl_buy_again".tr))])]); } 
/// Section Widget
Widget _buildOrderDetails5() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_order_id_aa1254ng".tr, style: CustomTextStyles.bodySmallPoppinsBlack900), SizedBox(height: 6.v), Text("msg_placed_on_14_dec2".tr, style: CustomTextStyles.bodySmallPoppinsGray50001), SizedBox(height: 11.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(padding: EdgeInsets.symmetric(horizontal: 4.h, vertical: 5.v), decoration: AppDecoration.fillBlueAC.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Column(mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.symmetric(horizontal: 1.h), child: _buildOrderDetails()), SizedBox(height: 5.v), Container(width: 146.h, margin: EdgeInsets.only(right: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(height: 69.v, width: 75.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.centerLeft, child: Container(height: 69.adaptSize, width: 69.adaptSize, margin: EdgeInsets.only(left: 1.h), decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(6.h)))), CustomImageView(imagePath: ImageConstant.imgDCc1, height: 40.v, width: 75.h, alignment: Alignment.topCenter, margin: EdgeInsets.only(top: 12.v))])), _buildF(moreCounter: "lbl_2_more".tr)]))])), Padding(padding: EdgeInsets.only(bottom: 9.v), child: _buildOrderDetails1(electricPackageText: "msg_electric_package".tr, descriptionText: "msg_headphone_buds2".tr, itemsCounterText: "lbl_05_items".tr, priceText: "lbl_150".tr, buyAgainText: "lbl_buy_again".tr))])]); } 
/// Section Widget
Widget _buildBottomBar() { return CustomBottomBar(onChanged: (BottomBarEnum type) {Get.toNamed(getCurrentRoute(type), id: 1);}); } 
/// Common widget
Widget _buildOrderDetails() { return SizedBox(width: 145.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(height: 69.adaptSize, width: 69.adaptSize, padding: EdgeInsets.all(5.h), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: CustomImageView(imagePath: ImageConstant.img5d02da5df552836, height: 58.adaptSize, width: 58.adaptSize, alignment: Alignment.center)), Container(height: 69.adaptSize, width: 69.adaptSize, padding: EdgeInsets.all(5.h), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: CustomImageView(imagePath: ImageConstant.imgHuaweiFreebuds, height: 58.adaptSize, width: 58.adaptSize, alignment: Alignment.center))])); } 
/// Common widget
Widget _buildF({required String moreCounter}) { return Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), color: appTheme.whiteA700, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder6), child: Container(height: 69.adaptSize, width: 69.adaptSize, decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.img9447441f632825, height: 47.v, width: 62.h, alignment: Alignment.center), Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 24.v), decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Text(moreCounter, style: CustomTextStyles.bodySmallPoppinsWhiteA70012_1.copyWith(color: appTheme.whiteA700))))]))); } 
/// Common widget
Widget _buildOrderDetails1({required String electricPackageText, required String descriptionText, required String itemsCounterText, required String priceText, required String buyAgainText, }) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(electricPackageText, style: CustomTextStyles.titleSmallPoppins.copyWith(color: appTheme.gray900)), SizedBox(width: 117.h, child: Text(descriptionText, maxLines: 4, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodySmallPoppinsGray500.copyWith(color: appTheme.gray500))), SizedBox(height: 6.v), Text(itemsCounterText, style: CustomTextStyles.bodySmallPoppinsGray90012.copyWith(color: appTheme.gray900)), SizedBox(height: 11.v), SizedBox(width: 155.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(priceText, style: CustomTextStyles.titleMediumMontserratRed300.copyWith(color: appTheme.red300)), Text(buyAgainText, style: CustomTextStyles.bodySmallPoppinsPrimary.copyWith(decoration: TextDecoration.underline, color: theme.colorScheme.primary))]))]); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.homePage; case BottomBarEnum.Cart: return AppRoutes.blankCartPage; case BottomBarEnum.Search: return "/"; case BottomBarEnum.Profile: return AppRoutes.profilePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.homePage: return HomePage(); case AppRoutes.blankCartPage: return BlankCartPage(); case AppRoutes.profilePage: return ProfilePage(); default: return DefaultWidget();} } 
/// Navigates to the completeOrderTabContainerScreen when the action is triggered.
onTapTxtCompleted() { Get.toNamed(AppRoutes.completeOrderTabContainerScreen, ); } 
 }
