import '../payment_one_screen/widgets/userprofile_item_widget.dart';import 'controller/payment_one_controller.dart';import 'models/userprofile_item_model.dart';import 'package:ecommerce_buyers_app/core/app_export.dart';import 'package:ecommerce_buyers_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:ecommerce_buyers_app/widgets/app_bar/appbar_title.dart';import 'package:ecommerce_buyers_app/widgets/app_bar/appbar_trailing_iconbutton_two.dart';import 'package:ecommerce_buyers_app/widgets/app_bar/custom_app_bar.dart';import 'package:ecommerce_buyers_app/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class PaymentOneScreen extends GetWidget<PaymentOneController> {const PaymentOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 8.v), child: Column(children: [SizedBox(height: 13.v), Expanded(child: SingleChildScrollView(child: _buildPaymentOne()))])), bottomNavigationBar: _buildConfirm())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 66.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowDownPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 7.v, bottom: 7.v), onTap: () {onTapArrowDown();}), centerTitle: true, title: AppbarTitle(text: "lbl_payment".tr), actions: [AppbarTrailingIconbuttonTwo(imagePath: ImageConstant.imgFramePrimarycontainer, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 16.v))]); } 
/// Section Widget
Widget _buildBillDetails() { return Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 2.h), child: Text("lbl_bill_details".tr, style: CustomTextStyles.titleMediumGray900))), SizedBox(height: 7.v), Padding(padding: EdgeInsets.symmetric(horizontal: 2.h), child: _buildSubtotalItems(subtotalText: "msg_subtotal_03_items".tr, priceText: "lbl_850_00".tr)), SizedBox(height: 3.v), Padding(padding: EdgeInsets.symmetric(horizontal: 2.h), child: _buildSubtotalItems(subtotalText: "lbl_discount".tr, priceText: "lbl_1_00".tr)), SizedBox(height: 4.v), Padding(padding: EdgeInsets.symmetric(horizontal: 2.h), child: _buildSubtotalItems(subtotalText: "lbl_shipping_cost".tr, priceText: "lbl_0_00".tr)), SizedBox(height: 8.v), Column(children: [Divider(color: appTheme.gray30001), SizedBox(height: 4.v), _buildSubtotalItems(subtotalText: "lbl_grand_total".tr, priceText: "lbl_849_00".tr)])]); } 
/// Section Widget
Widget _buildPaymentOne() { return Padding(padding: EdgeInsets.only(left: 22.h, right: 22.h, bottom: 5.v), child: Column(children: [Padding(padding: EdgeInsets.symmetric(horizontal: 2.h), child: _buildSubtotalItems(subtotalText: "lbl_payment_method".tr, priceText: "lbl_add".tr)), SizedBox(height: 13.v), Padding(padding: EdgeInsets.symmetric(horizontal: 2.h), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 20.v);}, itemCount: controller.paymentOneModelObj.value.userprofileItemList.value.length, itemBuilder: (context, index) {UserprofileItemModel model = controller.paymentOneModelObj.value.userprofileItemList.value[index]; return UserprofileItemWidget(model);}))), SizedBox(height: 40.v), _buildBillDetails()])); } 
/// Section Widget
Widget _buildConfirm() { return Container(margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 8.v), decoration: AppDecoration.outlineBlack900, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_total".tr, style: CustomTextStyles.bodyMediumGray900), Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_849_00".tr, style: CustomTextStyles.titleMediumRed300))])), CustomElevatedButton(width: 197.h, text: "lbl_confirm".tr, buttonTextStyle: CustomTextStyles.titleMediumWhiteA700_1)])); } 
/// Common widget
Widget _buildSubtotalItems({required String subtotalText, required String priceText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [RichText(text: TextSpan(children: [TextSpan(text: "lbl_subtotal".tr, style: theme.textTheme.bodyLarge), TextSpan(text: "lbl_03_items".tr, style: CustomTextStyles.bodyLargeGray60001)]), textAlign: TextAlign.left), Text(priceText, style: theme.textTheme.bodyLarge!.copyWith(color: appTheme.gray900))]); } 
/// Navigates to the cartOneScreen when the action is triggered.
onTapArrowDown() { Get.toNamed(AppRoutes.cartOneScreen, ); } 
 }
